# docker-compose.yml

version: '3.8'

services:
  # Serviço 1: O Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: estoque-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${ADMIN_DEFAULT_USERNAME}
      - POSTGRES_PASSWORD=${ADMIN_DEFAULT_PASSWORD}
      - POSTGRES_DB=estoque_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ADMIN_DEFAULT_USERNAME} -d estoque_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Serviço 2: A nossa Aplicação FastAPI
  app:
    container_name: estoque-app
    build: .
    # A porta 8000 já não é exposta ao exterior. Apenas o Nginx fala com ela.
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Serviço 3: O Proxy Reverso NGINX (O nosso "Recepcionista")
  nginx:
    image: nginx:alpine
    container_name: estoque-proxy
    ports:
      # Expõe a porta principal 80 do servidor ao mundo.
      - "80:80"
    volumes:
      # Mapeia o nosso ficheiro de configuração para dentro do container do Nginx.
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # Garante que o Nginx só inicia depois da nossa aplicação estar pronta.
      - app
    restart: unless-stopped

# Define os volumes que serão geridos pelo Docker.
volumes:
  postgres_data:

